# Railway Deployment Configuration
# This file configures your Django app for Railway hosting

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy.env]
# Railway will automatically set DATABASE_URL for MySQL
# You only need to add these custom environment variables:
# DJANGO_SECRET_KEY = "your-secret-key"
# DJANGO_DEBUG = "False"  
# ALLOWED_HOSTS = "your-app.railway.app"
