# Railway Deployment Configuration
# This file configures your Django app for Railway hosting

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"

[deploy.env]
# Railway will automatically set DATABASE_URL for MySQL
# Required environment variables to set in Railway dashboard:
# DJANGO_SECRET_KEY = "your-very-secret-key-here"
# DJANGO_DEBUG = "False"  
# ALLOWED_HOSTS = "your-app.railway.app,healthcheck.railway.app"
# 
# Optional (add when frontend is deployed):
# FRONTEND_URLS = "https://your-frontend.vercel.app"
